services:
  database:
    image: mysql:8.0
    container_name: database_containser
    restart: always
    environment:
      MYSQL_DATABASE: lg_db
      MYSQL_USER: lg_user
      MYSQL_PASSWORD: lg_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: